// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package terzo_assegnamento;

import java.util.ArrayList;
import java.util.Random;

import javax.persistence.*;

import terzo_assegnamento.Brano;
import terzo_assegnamento.Utenti;

@Entity
@Table(name = "UTENTE")

public class UtenteRegistrato extends Utenti {
	@Id
    @Column(name = "nickname")
	private String nickname;
	
    @Column(name = "email")
	private String email;
    
    @Column(name = "telefono")
	private int telefono;
    
    @Column(name = "portafoglio")
	private int portafoglio;
    
    @Column(name = "anno_iscrizione")
	private int anno_iscrizione;
    
    @Column(name = "Casa_Discografica")
	private boolean casaDiscografica;
    
    @Column(name = "Abbonamento")
	private boolean abbonamento;

    @Transient
	private ArrayList<Brano> branicaricatidautente = new ArrayList<Brano>();

    @Transient
	public Brano brano;
	
    @Transient
	Utenti utente = new Utenti();
	
	//metodi getters e setters
	public String getNickname() {
		return nickname;
	}


	public void setNickname(String nickname) {
		this.nickname = nickname;
	}
	
	public boolean getcasaDiscografica() {
		return casaDiscografica;
	}


	public void setcasaDiscografica(int dado) {
		if (dado % 2 == 0)
			this.casaDiscografica = true;
		else
			this.casaDiscografica = false;
	}


	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}


	public int getTelefono() {
		return telefono;
	}


	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}


	public Brano getBrano() {
		return brano;
	}


	public void setBrano(Brano brano) {
		this.brano = brano;
	}


	public Brano inserisci_brano(String titolo, String categoria,String portale) {
		this.brano = new Brano(titolo,categoria,getNickname(),portale);
		branicaricatidautente.add(brano);
		System.out.println("Brano caricato correttamente");
		return brano;
		
	}
	public ArrayList<Brano> brani_inseriti() {
		
		return branicaricatidautente;
	}
	
	public void metti_in_vendita(Brano brano, int prezzo) {
		if(this.abbonamento) {
			if(this.portafoglio -20 >=0) {
				this.portafoglio -= 20;//la messa in vendita ha un costo di 20€
				brano.setPrezzo(prezzo);
				System.out.println("Brano messo in vendita correttamente");
	
			}
			else 
				System.out.println("Non è possibile vendere il brano, denaro insufficiente");
			
		}
		else
			System.out.println("L'utente non è abilitato alla vendita dei brani");
			
		
	}


	public void gestisci_brano(Brano brano, String titolo, String categoria) {
		if(titolo != null && !titolo.isEmpty())
			brano.setTitolo(titolo);
		if(categoria != null && !categoria.isEmpty())
			brano.setCategoria(categoria);
	}
	

	@Override
	public UtenteRegistrato registra() {
		
		String casuale = utente.getSaltString();
		Random rnd = new Random();
		UtenteRegistrato utenteregistrato = new UtenteRegistrato();
		utenteregistrato.setNickname(casuale);
		utenteregistrato.setEmail(casuale+"@gmail.com");
		utenteregistrato.setTelefono(rnd.nextInt(39999999 - 30000000 + 1) + 30000000);
		utenteregistrato.setcasaDiscografica(rnd.nextInt(100 - 50 + 1) + 50);
		utenteregistrato.setAbbonamento(false);
		utenteregistrato.setAnno_iscrizione(rnd.nextInt(2018 - 1995 + 1) + 1995);
		if (utenteregistrato.getcasaDiscografica()) {
			utenteregistrato.setPortafoglio(rnd.nextInt(999999 - 100000 + 1) + 100000);
			//una casa discografica investe di più di un comune utente
		}
		else {
			utenteregistrato.setPortafoglio(rnd.nextInt(200));
		}
		
		return utenteregistrato;
		
	}


	public int getPortafoglio() {
		return portafoglio;
	}


	public void setPortafoglio(int portafoglio) {
		this.portafoglio = portafoglio;
	}


	public boolean isAbbonamento() {
		return abbonamento;
	}


	public void setAbbonamento(boolean abbonamento) {
		this.abbonamento = abbonamento;
	}


	public int getAnno_iscrizione() {
		return anno_iscrizione;
	}


	public void setAnno_iscrizione(int anno_iscrizione) {
		this.anno_iscrizione = anno_iscrizione;
	}

};
